# -*- coding: utf-8 -*-
"""Python basic assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Coa9b6CBmS-66Sbvz_jR8GUnLBPnmPs-
"""

#1

name = input("Enter your name: ")
age = int(input("Enter your age: "))
fav_num= int(input("Enter your favorite number: "))

print( name)
print(100-age)
print(2*fav_num)

#2

n = int(input("Enter a number: "))

if n % 2 == 0:
    print("Even")
else:
    print("Odd")

if n > 0:
    print("Positive")
elif n < 0:
    print("Negative")
else:
    print("Zero")

#3
for i in range(1, 51):
    if i % 2 == 0:
        print(i)


i = 1
while i <= 50:
    if i % 2 == 0:
        print(i)
    i += 1

#4
foods = []

for i in range(5):
    food = input("Enter favorite food: ")
    foods.append(food)

print(foods)

food_lengths = {}
for item in foods:
    food_lengths[item] = len(item)

print(food_lengths)

#5
def calculate_area(shape, d1, d2=None):
    if shape == "circle":
        return 3.14 * d1 * d1
    elif shape == "rectangle":
        return d1 * d2
    elif shape == "triangle":
        return 0.5 * d1 * d2

print(calculate_area("circle", 5))
print(calculate_area("rectangle", 4, 7))
print(calculate_area("triangle", 6, 8))

#6
s = input("Enter a sentence: ")

vowels = "aeiouAEIOU"
count = 0
for ch in s:
    if ch in vowels:
        count += 1

print("Vowels:", count)
print("Reversed:", s[::-1])
print("Uppercase:", s.upper())

#7

with open("data.txt", "w") as f:
    f.write("Hello, Python!\n")
    f.write("Learning file handling.\n")
    f.write("Python is fun!\n")

with open("data.txt", "r") as f:
    content = f.read()
    print(content)

#8

try:
    a = int(input("Enter first number: "))
    b = int(input("Enter second number: "))
    print("Result:", a / b)

except ZeroDivisionError:
    print("Cannot divide by zero.")

except ValueError:
    print("Invalid input. Please enter numbers only.")